name: Tests
on:
  push:
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}

      - name: Install npm dependencies
        run: npm ci

      - name: Unit Tests
        run: npm run test:unit

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       include:
# in mcp we do not support node 10 anymore
#         - nodeVersion: 10.x
#           testPlugins: "meteor"
#           testOptions: "--non-root"
#         - nodeVersion: 10.x
#           testPlugins: "docker,mongo,proxy,default"
#           testOptions: "--non-root"
         - nodeVersion: 22.x
           testPlugins: "meteor"
           testOptions: ""
         - nodeVersion: 22.x
           testPlugins: "docker,mongo,proxy,default"
           testOptions: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}

      - name: Install npm dependencies
        run: npm ci

      - name: Free up space
        run: sudo rm -rf /usr/local/lib/android

      - name: Run tests
        env:
          TEST_PLUGINS: ${{ matrix.testPlugins }}
          TEST_OPTIONS: ${{ matrix.testOptions }}
        run: |
          npm run test -- --plugins="$TEST_PLUGINS" $TEST_OPTIONS
